:toc:

= Documentation
Kadwalon Lobet, Guillaume de Maricourt.

== Project description
The project is a waterproof anemometer, low cost and with high precision (around 1 m/s sensitivity). +
Goal is to use it on a miniaturized, autonomous sail boat.

== Repo architecture and setups documentation
This repo use a simple folder architecture using topic seperated folders. +
Some of the folder implement a ``setup.adoc`` file which help in setting up the environment or the required tools.

See:

- link:../modeling/setup.adoc[Modeling setup file].
- link:../code/setup.adoc[Code setup file].
- link:../pcb/setup.adoc[PCB setup file].

== Project guidelines

In order to submit modification, you will need to submit pull requests and wait for approval. +
Submitted content must follow the architecture.

When submitting, ensure that:

- All CAO files (either modeling or PCB) are up-to-date, especially modeling production and projects files.
- Code is formatted correctyly using ``uncrustify`` see this link:../code/setup.adoc[document] to setup.
- Ensure that your branch is aligned with main (``git fetch | git rebase origin main``)
- Commits follow link:https://www.conventionalcommits.org/en/v1.0.0/[conventionnal commits specification].
- Components datasheets are up-to-date and stored according to PCB project name.

NOTE: ``docs/old`` folder is the first draft of a calibration tools. Goals was to assess impact of anemometer relative angle compared to wind plane. This project has been on hold since teachers wanted to make the actual anemometer and not rely on the industrial one. +
However those documents could be useful in the future and hence are kept.


== Theorical concepts

**TODO**